### ISSUE TITLE
Mobile App Bug fixes and Updates

### ISSUE THREAD

**Issue by anujtenani** [anujtenani/goaffpro#138]
List of issues to fix in upcoming app update

- [x] Points as a currency
- [x] Clickable referral link
- [x] Android App shows Creatives although Media Assets is deactivated in shopify app #22 
- [x] Remove affiliate earnings from Leaderboard if such is set in the admin panel #34 
- [x] share link has 'ref' parameter although ref is not in 'Referral Link Identifiers' list #23 
- [x] click on social icons closes app #23 
- [x] Apps always crash when sharing with facebook, whatsapp button, If I share using the share button the affiliate link doesn't come #38 

Notifications

- [x] Order notifications
- [x] Downline order notifications
- [x] New Downline recruitment notifications

**Comment by anujtenani** [comment]
Closing this issue as all the features are now met.
